manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: yoshikik1991
      url-base: https://github.com/yoshikik1991
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    #- name: zmk-module-ergokeys_mcu_nrf52
    #  remote: yoshikik1991
    #  revision: test
  self:
    path: config
    